---
swagger: "2.0"
info:
  description: "Retrieves, updates, and deletes cds data"
  version: "v1"
  title: "CDS"
  termsOfService: "dd"
  contact: {}
  license: {}
host: "cddirector.io"
basePath: "/cdd/cds/0000/v1"
tags:
- name: "cds"
  description: "changed-files-cds"
paths:
  /applications/{applicationId}/application-versions/{applicationVersionId}/changed-files:
    get:
      tags:
      - "changed-files-cds"
      summary: "Retrieve changed files per Application version from CDS"
      operationId: "getChangedFilesUsingGET"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - name: "applicationId"
        in: "path"
        description: "applicationId"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "ApplicationId"
      - name: "applicationVersionId"
        in: "path"
        description: "applicationVersionId"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "ApplicationVersionId"
      - name: "is_accessed"
        in: "query"
        description: "isAccessed"
        required: false
        type: "boolean"
        x-exportParamName: "IsAccessed"
        x-optionalDataType: "Bool"
      - name: "is_excluded"
        in: "query"
        description: "isExcluded"
        required: false
        type: "boolean"
        x-exportParamName: "IsExcluded"
        x-optionalDataType: "Bool"
      - name: "status"
        in: "query"
        description: "fileStatuses"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
        x-exportParamName: "Status"
      - name: "page_number"
        in: "query"
        description: "pageNumber"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "PageNumber"
        x-optionalDataType: "Int32"
      - name: "page_size"
        in: "query"
        description: "pageSize"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "PageSize"
        x-optionalDataType: "Int32"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/PagedResultDto«ChangedFileDto»"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
  /applications/{applicationId}/application-versions/{applicationVersionId}/test-suite-executions:
    get:
      tags:
      - "test-suite-executions"
      summary: "Retrieve all test suite executions"
      operationId: "getTestSuiteExecutionsUsingGET"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "applicationId"
        in: "path"
        description: "applicationId"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "ApplicationId"
      - name: "applicationVersionId"
        in: "path"
        description: "applicationVersionId"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "ApplicationVersionId"
      - name: "test_source"
        in: "query"
        description: "testSourceId"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "TestSource"
        x-optionalDataType: "Int64"
      - name: "sort_field"
        in: "query"
        description: "sortField"
        required: false
        type: "string"
        enum:
        - "startExecution"
        - "executionDuration"
        x-exportParamName: "SortField"
        x-optionalDataType: "String"
      - name: "sort_direction"
        in: "query"
        description: "sortDirection"
        required: false
        type: "string"
        enum:
        - "ASC"
        - "DESC"
        x-exportParamName: "SortDirection"
        x-optionalDataType: "String"
      - name: "filter"
        in: "query"
        description: "filter"
        required: false
        type: "string"
        x-exportParamName: "Filter"
        x-optionalDataType: "String"
      - name: "endpointId"
        in: "query"
        description: "endpointId"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "EndpointId"
        x-optionalDataType: "Int64"
      - name: "tag"
        in: "query"
        description: "tags"
        required: false
        type: "string"
        x-exportParamName: "Tag"
        x-optionalDataType: "String"
      - name: "environment"
        in: "query"
        description: "environmentId"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "Environment"
        x-optionalDataType: "Int64"
      - name: "release"
        in: "query"
        description: "releaseId"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "Release"
        x-optionalDataType: "Int64"
      - name: "phase"
        in: "query"
        description: "phaseIds"
        required: false
        type: "array"
        items:
          type: "integer"
          format: "int64"
        collectionFormat: "multi"
        x-exportParamName: "Phase"
      - name: "embed"
        in: "query"
        description: "embed"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
        x-exportParamName: "Embed"
      - name: "test_suite_execution_status"
        in: "query"
        description: "testSuiteExecutionStatuses"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
        x-exportParamName: "TestSuiteExecutionStatus"
      - name: "page_number"
        in: "query"
        description: "pageNumber"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "PageNumber"
        x-optionalDataType: "Int32"
      - name: "page_size"
        in: "query"
        description: "pageSize"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "PageSize"
        x-optionalDataType: "Int32"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/TestSuitesExecutionPagedDto"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
  /applications/{applicationId}/application-versions/{applicationVersionId}/test-suite-executions/{testSuiteExecutionsHexId}:
    get:
      tags:
      - "test-suite-executions"
      summary: "Retrieve test suite executions by id"
      operationId: "getTestSuiteByIdUsingGET"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "applicationId"
        in: "path"
        description: "applicationId"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "ApplicationId"
      - name: "applicationVersionId"
        in: "path"
        description: "applicationVersionId"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "ApplicationVersionId"
      - name: "testSuiteExecutionsHexId"
        in: "path"
        description: "testSuiteExecutionId"
        required: true
        type: "string"
        x-exportParamName: "TestSuiteExecutionsHexId"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/TestSuitesExecutionDto"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
  /applications/{applicationId}/application-versions/{applicationVersionId}/test-suite-results:
    get:
      tags:
      - "test-suite-results"
      summary: "Retrieve test suite result"
      operationId: "getTestSuiteResultUsingGET"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "applicationId"
        in: "path"
        description: "applicationId"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "ApplicationId"
      - name: "applicationVersionId"
        in: "path"
        description: "applicationVersionId"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "ApplicationVersionId"
      - name: "test_suite_execution_id"
        in: "query"
        description: "testSuiteResultId"
        required: false
        type: "string"
        x-exportParamName: "TestSuiteExecutionId"
        x-optionalDataType: "String"
      - name: "sort_field"
        in: "query"
        description: "sortField"
        required: false
        type: "string"
        x-exportParamName: "SortField"
        x-optionalDataType: "String"
      - name: "test_case_result_status"
        in: "query"
        description: "testCaseStatuses"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
        x-exportParamName: "TestCaseResultStatus"
      - name: "embed"
        in: "query"
        description: "embed"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
        x-exportParamName: "Embed"
      - name: "sort_direction"
        in: "query"
        description: "sortDirection"
        required: false
        type: "string"
        enum:
        - "ASC"
        - "DESC"
        x-exportParamName: "SortDirection"
        x-optionalDataType: "String"
      - name: "filter"
        in: "query"
        description: "filter"
        required: false
        type: "string"
        x-exportParamName: "Filter"
        x-optionalDataType: "String"
      - name: "endpoint_id"
        in: "query"
        description: "endpointId"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "EndpointId"
        x-optionalDataType: "Int64"
      - name: "plugin_id"
        in: "query"
        description: "pluginId"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "PluginId"
        x-optionalDataType: "Int64"
      - name: "tag"
        in: "query"
        description: "tags"
        required: false
        type: "string"
        x-exportParamName: "Tag"
        x-optionalDataType: "String"
      - name: "environment"
        in: "query"
        description: "environmentId"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "Environment"
        x-optionalDataType: "Int64"
      - name: "page_number"
        in: "query"
        description: "pageNumber"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "PageNumber"
        x-optionalDataType: "Int32"
      - name: "page_size"
        in: "query"
        description: "pageSize"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "PageSize"
        x-optionalDataType: "Int32"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/PagedResultDto«TestSuiteResultDto»"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
definitions:
  ChangedFileDto:
    properties:
      application:
        $ref: "#/definitions/NamedIdentifiableDto"
      applicationVersion:
        $ref: "#/definitions/NamedIdentifiableDto"
      fileId:
        type: "string"
      filename:
        type: "string"
      id:
        type: "string"
      lastAccessDate:
        type: "integer"
        format: "int64"
      lastChangeId:
        type: "string"
      lastCommitDate:
        type: "integer"
        format: "int64"
      status:
        type: "string"
  NamedVersionedIdentifiableDto:
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      project:
        $ref: "#/definitions/NamedIdentifiableDto"
      version:
        type: "string"
    example:
      name: "name"
      project:
        name: "name"
        id: 0
      id: 1
      version: "version"
  TestCaseResultDto:
    properties:
      changeId:
        type: "string"
      executionDuration:
        type: "integer"
        format: "int64"
      executionEndDate:
        type: "integer"
        format: "int64"
      executionStartDate:
        type: "integer"
        format: "int64"
      executionStatus:
        type: "string"
        enum:
        - "PASSED"
        - "FAILED"
        - "SKIPPED"
        - "ERROR"
        - "DISABLED"
      externalId:
        type: "string"
      id:
        type: "string"
      name:
        type: "string"
      resultMessage:
        type: "string"
      resultURL:
        type: "string"
      testSuiteResultId:
        type: "string"
    example:
      executionEndDate: 3
      testSuiteResultId: "testSuiteResultId"
      executionStatus: "PASSED"
      name: "name"
      externalId: "externalId"
      resultURL: "resultURL"
      changeId: "changeId"
      executionDuration: 6
      id: "id"
      resultMessage: "resultMessage"
      executionStartDate: 6
  StrategyCounterDto:
    properties:
      count:
        type: "integer"
        format: "int64"
      strategies:
        type: "array"
        items:
          type: "string"
    example:
      strategies:
      - "strategies"
      - "strategies"
      count: 4
  TestSuiteResultDto:
    properties:
      application:
        $ref: "#/definitions/NamedIdentifiableDto"
      applicationVersion:
        $ref: "#/definitions/NamedIdentifiableDto"
      buildNumber:
        type: "string"
      changeId:
        type: "string"
      commitId:
        type: "string"
      endpoint:
        $ref: "#/definitions/NamedIdentifiableDto"
      environments:
        type: "array"
        items:
          $ref: "#/definitions/NamedIdentifiableDto"
      executionDetailedStatusDescription:
        type: "string"
      executionDuration:
        type: "integer"
        format: "int64"
      executionEndDate:
        type: "integer"
        format: "int64"
      executionStartDate:
        type: "integer"
        format: "int64"
      executionStatusDescription:
        type: "string"
      externalId:
        type: "string"
      id:
        type: "string"
      name:
        type: "string"
      numberOfFailedTestCases:
        type: "integer"
        format: "int32"
      numberOfSuccessfulTestCases:
        type: "integer"
        format: "int32"
      phase:
        $ref: "#/definitions/NamedIdentifiableDto"
      phaseExecutionId:
        type: "string"
      phaseExecutionStartDate:
        type: "integer"
        format: "int64"
      plugin:
        $ref: "#/definitions/NamedIdentifiableDto"
      release:
        $ref: "#/definitions/NamedVersionedIdentifiableDto"
      resultURL:
        type: "string"
      strategies:
        type: "array"
        items:
          type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      task:
        $ref: "#/definitions/NamedIdentifiableDto"
      testCaseResults:
        type: "array"
        items:
          $ref: "#/definitions/TestCaseResultDto"
      testSuite:
        $ref: "#/definitions/StringIdentifiableDto"
      testSuiteExecutionEndDate:
        type: "integer"
        format: "int64"
      testSuiteExecutionOrder:
        type: "integer"
        format: "int64"
      testSuiteExecutionStatus:
        type: "string"
        enum:
        - "PASSED"
        - "FAILED"
        - "SKIPPED"
        - "ERROR"
        - "DISABLED"
      testSuitesExecutionId:
        type: "string"
    example:
      phaseExecutionStartDate: 9
      environments:
      - name: "name"
        id: 0
      - name: "name"
        id: 0
      release:
        name: "name"
        project:
          name: "name"
          id: 0
        id: 1
        version: "version"
      testSuite:
        name: "name"
        id: "id"
      changeId: "changeId"
      executionDuration: 5
      buildNumber: "buildNumber"
      endpoint:
        name: "name"
        id: 0
      numberOfFailedTestCases: 6
      resultURL: "resultURL"
      executionStatusDescription: "executionStatusDescription"
      testCaseResults:
      - executionEndDate: 3
        testSuiteResultId: "testSuiteResultId"
        executionStatus: "PASSED"
        name: "name"
        externalId: "externalId"
        resultURL: "resultURL"
        changeId: "changeId"
        executionDuration: 6
        id: "id"
        resultMessage: "resultMessage"
        executionStartDate: 6
      - executionEndDate: 3
        testSuiteResultId: "testSuiteResultId"
        executionStatus: "PASSED"
        name: "name"
        externalId: "externalId"
        resultURL: "resultURL"
        changeId: "changeId"
        executionDuration: 6
        id: "id"
        resultMessage: "resultMessage"
        executionStartDate: 6
      id: "id"
      testSuiteExecutionEndDate: 1
      executionStartDate: 9
      applicationVersion:
        name: "name"
        id: 0
      phase:
        name: "name"
        id: 0
      executionEndDate: 9
      phaseExecutionId: "phaseExecutionId"
      strategies:
      - "strategies"
      - "strategies"
      executionDetailedStatusDescription: "executionDetailedStatusDescription"
      externalId: "externalId"
      commitId: "commitId"
      tags:
      - "tags"
      - "tags"
      task:
        name: "name"
        id: 0
      application:
        name: "name"
        id: 0
      plugin:
        name: "name"
        id: 0
      numberOfSuccessfulTestCases: 8
      testSuitesExecutionId: "testSuitesExecutionId"
      name: "name"
      testSuiteExecutionOrder: 2
      testSuiteExecutionStatus: "PASSED"
  PluginCounterDto:
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      numberOfDisabledTestSuites:
        type: "integer"
        format: "int32"
      numberOfErrorTestSuites:
        type: "integer"
        format: "int32"
      numberOfFailedTestSuites:
        type: "integer"
        format: "int32"
      numberOfSkippedTestSuites:
        type: "integer"
        format: "int32"
      numberOfSuccessfulTestSuites:
        type: "integer"
        format: "int32"
    example:
      numberOfSkippedTestSuites: 6
      numberOfSuccessfulTestSuites: 7
      numberOfFailedTestSuites: 1
      numberOfErrorTestSuites: 1
      name: "name"
      id: 7
      numberOfDisabledTestSuites: 1
  PagedResultDto«ChangedFileDto»:
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/ChangedFileDto"
      pageNumber:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
      totalResultsCount:
        type: "integer"
        format: "int64"
  TestSuitesExecutionPagedDto:
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/TestSuitesExecutionDto"
      maxNumberOfTestSuites:
        type: "integer"
        format: "int64"
      pageNumber:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
      totalResultsCount:
        type: "integer"
        format: "int64"
    example:
      totalResultsCount: 6
      maxNumberOfTestSuites: 6
      pageNumber: 6
      data:
      - numberOfTestSuites: 4
        isOnlyIntelligentTestSuites: true
        numberOfErrorTestSuites: 2
        environments:
        - name: "name"
          id: 0
        - name: "name"
          id: 0
        release:
          name: "name"
          project:
            name: "name"
            id: 0
          id: 1
          version: "version"
        changeId: "changeId"
        executionDuration: 6
        buildNumber: "buildNumber"
        numberOfSkippedTestSuites: 3
        id: "id"
        executionStartDate: 5
        applicationVersion:
          name: "name"
          id: 0
        phase:
          name: "name"
          id: 0
        strategyCounters:
        - strategies:
          - "strategies"
          - "strategies"
          count: 4
        - strategies:
          - "strategies"
          - "strategies"
          count: 4
        numberOfFailedTestSuites: 7
        executionEndDate: 1
        numberOfIntelligentTestSuites: 9
        externalId: "externalId"
        commitId: "commitId"
        tags:
        - "tags"
        - "tags"
        numberOfSuccessfulTestSuites: 2
        task:
          name: "name"
          id: 0
        application:
          name: "name"
          id: 0
        testSuiteResults:
        - phaseExecutionStartDate: 9
          environments:
          - name: "name"
            id: 0
          - name: "name"
            id: 0
          release:
            name: "name"
            project:
              name: "name"
              id: 0
            id: 1
            version: "version"
          testSuite:
            name: "name"
            id: "id"
          changeId: "changeId"
          executionDuration: 5
          buildNumber: "buildNumber"
          endpoint:
            name: "name"
            id: 0
          numberOfFailedTestCases: 6
          resultURL: "resultURL"
          executionStatusDescription: "executionStatusDescription"
          testCaseResults:
          - executionEndDate: 3
            testSuiteResultId: "testSuiteResultId"
            executionStatus: "PASSED"
            name: "name"
            externalId: "externalId"
            resultURL: "resultURL"
            changeId: "changeId"
            executionDuration: 6
            id: "id"
            resultMessage: "resultMessage"
            executionStartDate: 6
          - executionEndDate: 3
            testSuiteResultId: "testSuiteResultId"
            executionStatus: "PASSED"
            name: "name"
            externalId: "externalId"
            resultURL: "resultURL"
            changeId: "changeId"
            executionDuration: 6
            id: "id"
            resultMessage: "resultMessage"
            executionStartDate: 6
          id: "id"
          testSuiteExecutionEndDate: 1
          executionStartDate: 9
          applicationVersion:
            name: "name"
            id: 0
          phase:
            name: "name"
            id: 0
          executionEndDate: 9
          phaseExecutionId: "phaseExecutionId"
          strategies:
          - "strategies"
          - "strategies"
          executionDetailedStatusDescription: "executionDetailedStatusDescription"
          externalId: "externalId"
          commitId: "commitId"
          tags:
          - "tags"
          - "tags"
          task:
            name: "name"
            id: 0
          application:
            name: "name"
            id: 0
          plugin:
            name: "name"
            id: 0
          numberOfSuccessfulTestCases: 8
          testSuitesExecutionId: "testSuitesExecutionId"
          name: "name"
          testSuiteExecutionOrder: 2
          testSuiteExecutionStatus: "PASSED"
        - phaseExecutionStartDate: 9
          environments:
          - name: "name"
            id: 0
          - name: "name"
            id: 0
          release:
            name: "name"
            project:
              name: "name"
              id: 0
            id: 1
            version: "version"
          testSuite:
            name: "name"
            id: "id"
          changeId: "changeId"
          executionDuration: 5
          buildNumber: "buildNumber"
          endpoint:
            name: "name"
            id: 0
          numberOfFailedTestCases: 6
          resultURL: "resultURL"
          executionStatusDescription: "executionStatusDescription"
          testCaseResults:
          - executionEndDate: 3
            testSuiteResultId: "testSuiteResultId"
            executionStatus: "PASSED"
            name: "name"
            externalId: "externalId"
            resultURL: "resultURL"
            changeId: "changeId"
            executionDuration: 6
            id: "id"
            resultMessage: "resultMessage"
            executionStartDate: 6
          - executionEndDate: 3
            testSuiteResultId: "testSuiteResultId"
            executionStatus: "PASSED"
            name: "name"
            externalId: "externalId"
            resultURL: "resultURL"
            changeId: "changeId"
            executionDuration: 6
            id: "id"
            resultMessage: "resultMessage"
            executionStartDate: 6
          id: "id"
          testSuiteExecutionEndDate: 1
          executionStartDate: 9
          applicationVersion:
            name: "name"
            id: 0
          phase:
            name: "name"
            id: 0
          executionEndDate: 9
          phaseExecutionId: "phaseExecutionId"
          strategies:
          - "strategies"
          - "strategies"
          executionDetailedStatusDescription: "executionDetailedStatusDescription"
          externalId: "externalId"
          commitId: "commitId"
          tags:
          - "tags"
          - "tags"
          task:
            name: "name"
            id: 0
          application:
            name: "name"
            id: 0
          plugin:
            name: "name"
            id: 0
          numberOfSuccessfulTestCases: 8
          testSuitesExecutionId: "testSuitesExecutionId"
          name: "name"
          testSuiteExecutionOrder: 2
          testSuiteExecutionStatus: "PASSED"
        name: "name"
        pluginsCounter:
        - numberOfSkippedTestSuites: 6
          numberOfSuccessfulTestSuites: 7
          numberOfFailedTestSuites: 1
          numberOfErrorTestSuites: 1
          name: "name"
          id: 7
          numberOfDisabledTestSuites: 1
        - numberOfSkippedTestSuites: 6
          numberOfSuccessfulTestSuites: 7
          numberOfFailedTestSuites: 1
          numberOfErrorTestSuites: 1
          name: "name"
          id: 7
          numberOfDisabledTestSuites: 1
        numberOfDisabledTestSuites: 5
      - numberOfTestSuites: 4
        isOnlyIntelligentTestSuites: true
        numberOfErrorTestSuites: 2
        environments:
        - name: "name"
          id: 0
        - name: "name"
          id: 0
        release:
          name: "name"
          project:
            name: "name"
            id: 0
          id: 1
          version: "version"
        changeId: "changeId"
        executionDuration: 6
        buildNumber: "buildNumber"
        numberOfSkippedTestSuites: 3
        id: "id"
        executionStartDate: 5
        applicationVersion:
          name: "name"
          id: 0
        phase:
          name: "name"
          id: 0
        strategyCounters:
        - strategies:
          - "strategies"
          - "strategies"
          count: 4
        - strategies:
          - "strategies"
          - "strategies"
          count: 4
        numberOfFailedTestSuites: 7
        executionEndDate: 1
        numberOfIntelligentTestSuites: 9
        externalId: "externalId"
        commitId: "commitId"
        tags:
        - "tags"
        - "tags"
        numberOfSuccessfulTestSuites: 2
        task:
          name: "name"
          id: 0
        application:
          name: "name"
          id: 0
        testSuiteResults:
        - phaseExecutionStartDate: 9
          environments:
          - name: "name"
            id: 0
          - name: "name"
            id: 0
          release:
            name: "name"
            project:
              name: "name"
              id: 0
            id: 1
            version: "version"
          testSuite:
            name: "name"
            id: "id"
          changeId: "changeId"
          executionDuration: 5
          buildNumber: "buildNumber"
          endpoint:
            name: "name"
            id: 0
          numberOfFailedTestCases: 6
          resultURL: "resultURL"
          executionStatusDescription: "executionStatusDescription"
          testCaseResults:
          - executionEndDate: 3
            testSuiteResultId: "testSuiteResultId"
            executionStatus: "PASSED"
            name: "name"
            externalId: "externalId"
            resultURL: "resultURL"
            changeId: "changeId"
            executionDuration: 6
            id: "id"
            resultMessage: "resultMessage"
            executionStartDate: 6
          - executionEndDate: 3
            testSuiteResultId: "testSuiteResultId"
            executionStatus: "PASSED"
            name: "name"
            externalId: "externalId"
            resultURL: "resultURL"
            changeId: "changeId"
            executionDuration: 6
            id: "id"
            resultMessage: "resultMessage"
            executionStartDate: 6
          id: "id"
          testSuiteExecutionEndDate: 1
          executionStartDate: 9
          applicationVersion:
            name: "name"
            id: 0
          phase:
            name: "name"
            id: 0
          executionEndDate: 9
          phaseExecutionId: "phaseExecutionId"
          strategies:
          - "strategies"
          - "strategies"
          executionDetailedStatusDescription: "executionDetailedStatusDescription"
          externalId: "externalId"
          commitId: "commitId"
          tags:
          - "tags"
          - "tags"
          task:
            name: "name"
            id: 0
          application:
            name: "name"
            id: 0
          plugin:
            name: "name"
            id: 0
          numberOfSuccessfulTestCases: 8
          testSuitesExecutionId: "testSuitesExecutionId"
          name: "name"
          testSuiteExecutionOrder: 2
          testSuiteExecutionStatus: "PASSED"
        - phaseExecutionStartDate: 9
          environments:
          - name: "name"
            id: 0
          - name: "name"
            id: 0
          release:
            name: "name"
            project:
              name: "name"
              id: 0
            id: 1
            version: "version"
          testSuite:
            name: "name"
            id: "id"
          changeId: "changeId"
          executionDuration: 5
          buildNumber: "buildNumber"
          endpoint:
            name: "name"
            id: 0
          numberOfFailedTestCases: 6
          resultURL: "resultURL"
          executionStatusDescription: "executionStatusDescription"
          testCaseResults:
          - executionEndDate: 3
            testSuiteResultId: "testSuiteResultId"
            executionStatus: "PASSED"
            name: "name"
            externalId: "externalId"
            resultURL: "resultURL"
            changeId: "changeId"
            executionDuration: 6
            id: "id"
            resultMessage: "resultMessage"
            executionStartDate: 6
          - executionEndDate: 3
            testSuiteResultId: "testSuiteResultId"
            executionStatus: "PASSED"
            name: "name"
            externalId: "externalId"
            resultURL: "resultURL"
            changeId: "changeId"
            executionDuration: 6
            id: "id"
            resultMessage: "resultMessage"
            executionStartDate: 6
          id: "id"
          testSuiteExecutionEndDate: 1
          executionStartDate: 9
          applicationVersion:
            name: "name"
            id: 0
          phase:
            name: "name"
            id: 0
          executionEndDate: 9
          phaseExecutionId: "phaseExecutionId"
          strategies:
          - "strategies"
          - "strategies"
          executionDetailedStatusDescription: "executionDetailedStatusDescription"
          externalId: "externalId"
          commitId: "commitId"
          tags:
          - "tags"
          - "tags"
          task:
            name: "name"
            id: 0
          application:
            name: "name"
            id: 0
          plugin:
            name: "name"
            id: 0
          numberOfSuccessfulTestCases: 8
          testSuitesExecutionId: "testSuitesExecutionId"
          name: "name"
          testSuiteExecutionOrder: 2
          testSuiteExecutionStatus: "PASSED"
        name: "name"
        pluginsCounter:
        - numberOfSkippedTestSuites: 6
          numberOfSuccessfulTestSuites: 7
          numberOfFailedTestSuites: 1
          numberOfErrorTestSuites: 1
          name: "name"
          id: 7
          numberOfDisabledTestSuites: 1
        - numberOfSkippedTestSuites: 6
          numberOfSuccessfulTestSuites: 7
          numberOfFailedTestSuites: 1
          numberOfErrorTestSuites: 1
          name: "name"
          id: 7
          numberOfDisabledTestSuites: 1
        numberOfDisabledTestSuites: 5
      pageSize: 5
  StringIdentifiableDto:
    properties:
      id:
        type: "string"
      name:
        type: "string"
    example:
      name: "name"
      id: "id"
  PagedResultDto«TestSuiteResultDto»:
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/TestSuiteResultDto"
      pageNumber:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
      totalResultsCount:
        type: "integer"
        format: "int64"
    example:
      totalResultsCount: 1
      pageNumber: 0
      data:
      - phaseExecutionStartDate: 9
        environments:
        - name: "name"
          id: 0
        - name: "name"
          id: 0
        release:
          name: "name"
          project:
            name: "name"
            id: 0
          id: 1
          version: "version"
        testSuite:
          name: "name"
          id: "id"
        changeId: "changeId"
        executionDuration: 5
        buildNumber: "buildNumber"
        endpoint:
          name: "name"
          id: 0
        numberOfFailedTestCases: 6
        resultURL: "resultURL"
        executionStatusDescription: "executionStatusDescription"
        testCaseResults:
        - executionEndDate: 3
          testSuiteResultId: "testSuiteResultId"
          executionStatus: "PASSED"
          name: "name"
          externalId: "externalId"
          resultURL: "resultURL"
          changeId: "changeId"
          executionDuration: 6
          id: "id"
          resultMessage: "resultMessage"
          executionStartDate: 6
        - executionEndDate: 3
          testSuiteResultId: "testSuiteResultId"
          executionStatus: "PASSED"
          name: "name"
          externalId: "externalId"
          resultURL: "resultURL"
          changeId: "changeId"
          executionDuration: 6
          id: "id"
          resultMessage: "resultMessage"
          executionStartDate: 6
        id: "id"
        testSuiteExecutionEndDate: 1
        executionStartDate: 9
        applicationVersion:
          name: "name"
          id: 0
        phase:
          name: "name"
          id: 0
        executionEndDate: 9
        phaseExecutionId: "phaseExecutionId"
        strategies:
        - "strategies"
        - "strategies"
        executionDetailedStatusDescription: "executionDetailedStatusDescription"
        externalId: "externalId"
        commitId: "commitId"
        tags:
        - "tags"
        - "tags"
        task:
          name: "name"
          id: 0
        application:
          name: "name"
          id: 0
        plugin:
          name: "name"
          id: 0
        numberOfSuccessfulTestCases: 8
        testSuitesExecutionId: "testSuitesExecutionId"
        name: "name"
        testSuiteExecutionOrder: 2
        testSuiteExecutionStatus: "PASSED"
      - phaseExecutionStartDate: 9
        environments:
        - name: "name"
          id: 0
        - name: "name"
          id: 0
        release:
          name: "name"
          project:
            name: "name"
            id: 0
          id: 1
          version: "version"
        testSuite:
          name: "name"
          id: "id"
        changeId: "changeId"
        executionDuration: 5
        buildNumber: "buildNumber"
        endpoint:
          name: "name"
          id: 0
        numberOfFailedTestCases: 6
        resultURL: "resultURL"
        executionStatusDescription: "executionStatusDescription"
        testCaseResults:
        - executionEndDate: 3
          testSuiteResultId: "testSuiteResultId"
          executionStatus: "PASSED"
          name: "name"
          externalId: "externalId"
          resultURL: "resultURL"
          changeId: "changeId"
          executionDuration: 6
          id: "id"
          resultMessage: "resultMessage"
          executionStartDate: 6
        - executionEndDate: 3
          testSuiteResultId: "testSuiteResultId"
          executionStatus: "PASSED"
          name: "name"
          externalId: "externalId"
          resultURL: "resultURL"
          changeId: "changeId"
          executionDuration: 6
          id: "id"
          resultMessage: "resultMessage"
          executionStartDate: 6
        id: "id"
        testSuiteExecutionEndDate: 1
        executionStartDate: 9
        applicationVersion:
          name: "name"
          id: 0
        phase:
          name: "name"
          id: 0
        executionEndDate: 9
        phaseExecutionId: "phaseExecutionId"
        strategies:
        - "strategies"
        - "strategies"
        executionDetailedStatusDescription: "executionDetailedStatusDescription"
        externalId: "externalId"
        commitId: "commitId"
        tags:
        - "tags"
        - "tags"
        task:
          name: "name"
          id: 0
        application:
          name: "name"
          id: 0
        plugin:
          name: "name"
          id: 0
        numberOfSuccessfulTestCases: 8
        testSuitesExecutionId: "testSuitesExecutionId"
        name: "name"
        testSuiteExecutionOrder: 2
        testSuiteExecutionStatus: "PASSED"
      pageSize: 6
  NamedIdentifiableDto:
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    example:
      name: "name"
      id: 0
  TestSuitesExecutionDto:
    properties:
      application:
        $ref: "#/definitions/NamedIdentifiableDto"
      applicationVersion:
        $ref: "#/definitions/NamedIdentifiableDto"
      buildNumber:
        type: "string"
      changeId:
        type: "string"
      commitId:
        type: "string"
      environments:
        type: "array"
        items:
          $ref: "#/definitions/NamedIdentifiableDto"
      executionDuration:
        type: "integer"
        format: "int64"
      executionEndDate:
        type: "integer"
        format: "int64"
      executionStartDate:
        type: "integer"
        format: "int64"
      externalId:
        type: "string"
      id:
        type: "string"
      isOnlyIntelligentTestSuites:
        type: "boolean"
      name:
        type: "string"
      numberOfDisabledTestSuites:
        type: "integer"
        format: "int64"
      numberOfErrorTestSuites:
        type: "integer"
        format: "int64"
      numberOfFailedTestSuites:
        type: "integer"
        format: "int64"
      numberOfIntelligentTestSuites:
        type: "integer"
        format: "int64"
      numberOfSkippedTestSuites:
        type: "integer"
        format: "int64"
      numberOfSuccessfulTestSuites:
        type: "integer"
        format: "int64"
      numberOfTestSuites:
        type: "integer"
        format: "int64"
      phase:
        $ref: "#/definitions/NamedIdentifiableDto"
      pluginsCounter:
        type: "array"
        items:
          $ref: "#/definitions/PluginCounterDto"
      release:
        $ref: "#/definitions/NamedVersionedIdentifiableDto"
      strategyCounters:
        type: "array"
        items:
          $ref: "#/definitions/StrategyCounterDto"
      tags:
        type: "array"
        items:
          type: "string"
      task:
        $ref: "#/definitions/NamedIdentifiableDto"
      testSuiteResults:
        type: "array"
        items:
          $ref: "#/definitions/TestSuiteResultDto"
    example:
      numberOfTestSuites: 4
      isOnlyIntelligentTestSuites: true
      numberOfErrorTestSuites: 2
      environments:
      - name: "name"
        id: 0
      - name: "name"
        id: 0
      release:
        name: "name"
        project:
          name: "name"
          id: 0
        id: 1
        version: "version"
      changeId: "changeId"
      executionDuration: 6
      buildNumber: "buildNumber"
      numberOfSkippedTestSuites: 3
      id: "id"
      executionStartDate: 5
      applicationVersion:
        name: "name"
        id: 0
      phase:
        name: "name"
        id: 0
      strategyCounters:
      - strategies:
        - "strategies"
        - "strategies"
        count: 4
      - strategies:
        - "strategies"
        - "strategies"
        count: 4
      numberOfFailedTestSuites: 7
      executionEndDate: 1
      numberOfIntelligentTestSuites: 9
      externalId: "externalId"
      commitId: "commitId"
      tags:
      - "tags"
      - "tags"
      numberOfSuccessfulTestSuites: 2
      task:
        name: "name"
        id: 0
      application:
        name: "name"
        id: 0
      testSuiteResults:
      - phaseExecutionStartDate: 9
        environments:
        - name: "name"
          id: 0
        - name: "name"
          id: 0
        release:
          name: "name"
          project:
            name: "name"
            id: 0
          id: 1
          version: "version"
        testSuite:
          name: "name"
          id: "id"
        changeId: "changeId"
        executionDuration: 5
        buildNumber: "buildNumber"
        endpoint:
          name: "name"
          id: 0
        numberOfFailedTestCases: 6
        resultURL: "resultURL"
        executionStatusDescription: "executionStatusDescription"
        testCaseResults:
        - executionEndDate: 3
          testSuiteResultId: "testSuiteResultId"
          executionStatus: "PASSED"
          name: "name"
          externalId: "externalId"
          resultURL: "resultURL"
          changeId: "changeId"
          executionDuration: 6
          id: "id"
          resultMessage: "resultMessage"
          executionStartDate: 6
        - executionEndDate: 3
          testSuiteResultId: "testSuiteResultId"
          executionStatus: "PASSED"
          name: "name"
          externalId: "externalId"
          resultURL: "resultURL"
          changeId: "changeId"
          executionDuration: 6
          id: "id"
          resultMessage: "resultMessage"
          executionStartDate: 6
        id: "id"
        testSuiteExecutionEndDate: 1
        executionStartDate: 9
        applicationVersion:
          name: "name"
          id: 0
        phase:
          name: "name"
          id: 0
        executionEndDate: 9
        phaseExecutionId: "phaseExecutionId"
        strategies:
        - "strategies"
        - "strategies"
        executionDetailedStatusDescription: "executionDetailedStatusDescription"
        externalId: "externalId"
        commitId: "commitId"
        tags:
        - "tags"
        - "tags"
        task:
          name: "name"
          id: 0
        application:
          name: "name"
          id: 0
        plugin:
          name: "name"
          id: 0
        numberOfSuccessfulTestCases: 8
        testSuitesExecutionId: "testSuitesExecutionId"
        name: "name"
        testSuiteExecutionOrder: 2
        testSuiteExecutionStatus: "PASSED"
      - phaseExecutionStartDate: 9
        environments:
        - name: "name"
          id: 0
        - name: "name"
          id: 0
        release:
          name: "name"
          project:
            name: "name"
            id: 0
          id: 1
          version: "version"
        testSuite:
          name: "name"
          id: "id"
        changeId: "changeId"
        executionDuration: 5
        buildNumber: "buildNumber"
        endpoint:
          name: "name"
          id: 0
        numberOfFailedTestCases: 6
        resultURL: "resultURL"
        executionStatusDescription: "executionStatusDescription"
        testCaseResults:
        - executionEndDate: 3
          testSuiteResultId: "testSuiteResultId"
          executionStatus: "PASSED"
          name: "name"
          externalId: "externalId"
          resultURL: "resultURL"
          changeId: "changeId"
          executionDuration: 6
          id: "id"
          resultMessage: "resultMessage"
          executionStartDate: 6
        - executionEndDate: 3
          testSuiteResultId: "testSuiteResultId"
          executionStatus: "PASSED"
          name: "name"
          externalId: "externalId"
          resultURL: "resultURL"
          changeId: "changeId"
          executionDuration: 6
          id: "id"
          resultMessage: "resultMessage"
          executionStartDate: 6
        id: "id"
        testSuiteExecutionEndDate: 1
        executionStartDate: 9
        applicationVersion:
          name: "name"
          id: 0
        phase:
          name: "name"
          id: 0
        executionEndDate: 9
        phaseExecutionId: "phaseExecutionId"
        strategies:
        - "strategies"
        - "strategies"
        executionDetailedStatusDescription: "executionDetailedStatusDescription"
        externalId: "externalId"
        commitId: "commitId"
        tags:
        - "tags"
        - "tags"
        task:
          name: "name"
          id: 0
        application:
          name: "name"
          id: 0
        plugin:
          name: "name"
          id: 0
        numberOfSuccessfulTestCases: 8
        testSuitesExecutionId: "testSuitesExecutionId"
        name: "name"
        testSuiteExecutionOrder: 2
        testSuiteExecutionStatus: "PASSED"
      name: "name"
      pluginsCounter:
      - numberOfSkippedTestSuites: 6
        numberOfSuccessfulTestSuites: 7
        numberOfFailedTestSuites: 1
        numberOfErrorTestSuites: 1
        name: "name"
        id: 7
        numberOfDisabledTestSuites: 1
      - numberOfSkippedTestSuites: 6
        numberOfSuccessfulTestSuites: 7
        numberOfFailedTestSuites: 1
        numberOfErrorTestSuites: 1
        name: "name"
        id: 7
        numberOfDisabledTestSuites: 1
      numberOfDisabledTestSuites: 5
